name: inflack_limited
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  google_fonts: ^2.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/images/login/
    - assets/icons/

  fonts:
    - family: Charukola Regular
      fonts:
        - asset: fonts/Charukola-Regular.ttf